<?php
/**
 * Copyright © 2011-2018 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * 
 * See COPYING.txt for license details.
 */
/** @var $block \Faonni\ContactMap\Block\Map */
?>
<?php if ($block->isEnabled()) : ?>
<div id="contact-map" class="page-map" data-marker="<?php echo $block->getMarkerPosition() ?>"></div>

<script type="text/javascript">
	require(
		[
		  'jquery',
          'Faonni_ContactMap/js/map',
          <?= ($block->getMapType() == 'mapbox') ? "'mapboxgl'" : ''; ?>
        ],
		function($, map, mapboxgl){
			map.init({
              apiKey: '<?= $block->getApiKey(); ?>',
              mapType: '<?= $block->getMapType(); ?>',
              zoom: <?= $block->getZoom(); ?>,
			});
		});
</script>
<?php endif; ?>
