<?php
/** @var $block \Faonni\ContactMap\Block\Popup */

$storeInfo = $block->getStoreInformation();
?>
<?php if ($block->isEnabled()) : ?>
    <div id="contact-map-popup" class="page-map__popup">
        <?php if ($block->showAddress()): ?>
            <address class="page-map__address">
                <?= $storeInfo->getFormattedAddress(); ?>
            </address>
        <?php endif; ?>

        <?php if($block->getContent()): ?>
        <div class="page-map__content">
            <?= $block->getContent(); ?>
        </div>
        <?php endif; ?>

        <?php if ($block->getShow_directions_link()): ?>
            <a href="<?= $block->getDirectionsURL(); ?>" target="_blank">
                <?= $block->escapeHtml(__('Click here for Directions')); ?>
            </a>
        <?php endif; ?>
    </div>
<?php endif; ?>
