<?php
/** @var $block \Faonni\ContactMap\Block\Popup */
?>
<?php if ($block->isEnabled()) : ?>
    <div id="contact-map-popup" class="page-map__popup">
        <?php if ($block->showAddress() && !empty($block->getFormattedAddress())): ?>
            <address class="page-map__address">
                <?= $block->getFormattedAddress(); ?>
            </address>
        <?php endif; ?>

        <?php if($block->getContent()): ?>
        <div class="page-map__content">
            <?= $block->getContent(); ?>
        </div>
        <?php endif; ?>

        <?php if ($block->getShow_directions_link() && !empty($block->getDirectionsURL())): ?>
            <a href="<?= $block->getDirectionsURL(); ?>" target="_blank" class="action primary">
                <?= $block->escapeHtml(__('Directions')); ?>
            </a>
        <?php endif; ?>
    </div>
<?php endif; ?>
